"""Cache a true spherical Wiener/Feeney response channel into HDF5 datasets.

Assumptions
-----------
* The target HDF5s are patch-space products built from known CAMB realization
  seeds and stored patch centers. Those seeds let us reconstruct the same clean
  CMB realization on the sphere.
* The matched-filter operator is the true spherical Wiener/Feeney bank from
  McEwen et al. (2012)-style axisymmetric filtering, implemented with the
  remediated beam and pixel-window policy from this repo.
* Exact patch-noise realizations are not stored in the training HDF5
  provenance. By default this cache therefore reconstructs the signal+CMB sky
  on the sphere and omits stochastic patch-noise draws. This yields a
  physically grounded spherical feature channel, but not an exact replay of the
  original patch observation.
* Positive examples in the base HDF5s were generated by injecting onto flat
  patches. Re-injecting the corresponding signal on the sphere can introduce a
  projection mismatch at large radius or large off-center distance. That risk
  must be audited before promoting the channel to a paper claim.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import datetime as dt
import json
from pathlib import Path
from typing import Any

import h5py
import healpy as hp
import numpy as np

from phase2_observing_model import camb_tt_cls, inject_signal_on_sphere, project_patch
from phase3_classical_filters import (
    precompute_wiener_feeney_filter_bank,
    validate_cmb_map,
)
from phase3_method_registry import WIENER_FEENEY_MATCHED_FILTER, method_metadata
from phase3_same_grid_fullsky_benchmark import (
    CmbMapCache,
    apply_observing_transfer,
    fullsky_noise_sigma_k_per_pixel,
    parse_json_attr,
    row_noise_rng,
)
from phase_config import PATCH_PIX


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATASETS = (
    PROJECT_ROOT / "data" / "remediated_v1" / "training_data.h5",
)
DEFAULT_DATASET_PATH = "features/wiener_feeney_response"
DEFAULT_THETA_GRID_DEG = (5.0, 10.0, 15.0, 20.0, 25.0)
WORKER_STATE: dict[str, Any] = {}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Cache a true spherical Wiener response channel into HDF5 files.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--h5", action="append", default=[], help="HDF5 file to update. Can be repeated.")
    parser.add_argument("--dataset", type=str, default=DEFAULT_DATASET_PATH)
    parser.add_argument("--theta-grid-deg", type=str, default="", help="Comma list; empty uses summary/theta grid.")
    parser.add_argument("--lmax", type=int, default=0, help="0 means 3*nside-1.")
    parser.add_argument("--quadrature-order", type=int, default=1024)
    parser.add_argument("--cmb-realization-cache", type=int, default=4)
    parser.add_argument("--compression", type=str, default="lzf", choices=["none", "lzf", "gzip"])
    parser.add_argument("--dtype", type=str, default="float32", choices=["float32", "float16"])
    parser.add_argument("--workers", type=int, default=1, help="Worker processes for spherical response caching.")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--row-start", type=int, default=0)
    parser.add_argument("--row-stop", type=int, default=0, help="0 means the end of the dataset.")
    parser.add_argument(
        "--include-surrogate-noise",
        action="store_true",
        help=(
            "Inject a deterministic surrogate full-sky white-noise realization using the "
            "stored noise depth and row index. This does not reproduce the original patch noise."
        ),
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def parse_float_list(text: str) -> tuple[float, ...]:
    return tuple(float(item.strip()) for item in str(text).split(",") if item.strip())


def validate_args(args: argparse.Namespace) -> None:
    if int(args.lmax) < 0:
        raise ValueError("--lmax must be non-negative.")
    if int(args.quadrature_order) <= 0:
        raise ValueError("--quadrature-order must be positive.")
    if int(args.cmb_realization_cache) <= 0:
        raise ValueError("--cmb-realization-cache must be positive.")
    if int(args.workers) <= 0:
        raise ValueError("--workers must be positive.")
    if int(args.row_start) < 0:
        raise ValueError("--row-start must be non-negative.")
    if int(args.row_stop) < 0:
        raise ValueError("--row-stop must be non-negative.")
    args.theta_grid_values = parse_float_list(args.theta_grid_deg) if args.theta_grid_deg else tuple()
    args.h5_paths = [Path(path).expanduser().resolve() for path in (args.h5 or DEFAULT_DATASETS)]
    missing = [str(path) for path in args.h5_paths if not path.exists()]
    if missing:
        raise FileNotFoundError(f"Missing HDF5 input(s): {missing}")


def compression_kwargs(name: str) -> dict[str, Any]:
    if name == "none":
        return {}
    if name == "gzip":
        return {"compression": "gzip", "shuffle": True}
    return {"compression": "lzf", "shuffle": True}


def ensure_parent_group(h5: h5py.File, dataset_path: str) -> None:
    parent = str(Path(dataset_path).parent).strip(".")
    if parent and parent != "/":
        h5.require_group(parent)


def load_summary(path: Path) -> dict[str, Any]:
    with h5py.File(path, "r") as h5:
        if "summary" not in h5:
            raise ValueError(f"{path} is missing summary attrs.")
        summary = dict(h5["summary"].attrs)
    out = dict(summary)
    for key in ("theta_grid_deg", "camb_params"):
        if key in out:
            out[key] = parse_json_attr(out[key])
    return out


def resolve_camb_params(path: Path, summary: dict[str, Any]) -> dict[str, Any]:
    """Return CAMB/synfast provenance, falling back to remediated provenance JSON."""

    camb_params = dict(summary.get("camb_params", {}))
    seeds = list(camb_params.get("seeds", []))
    if seeds:
        return camb_params

    fallback_paths = [
        path.parent / "observing_model_provenance.json",
        PROJECT_ROOT / "data" / "remediated_v1" / "observing_model_provenance.json",
    ]
    for fallback in fallback_paths:
        if fallback.exists():
            payload = json.loads(fallback.read_text(encoding="utf-8"))
            if list(payload.get("seeds", [])):
                merged = dict(payload)
                merged.update({key: value for key, value in camb_params.items() if key != "seeds"})
                return merged
    raise ValueError(
        f"{path} summary camb_params does not contain seeds and no observing_model_provenance.json fallback was found."
    )


def resolve_theta_grid(summary: dict[str, Any], explicit: tuple[float, ...]) -> tuple[float, ...]:
    if explicit:
        return explicit
    if "theta_grid_deg" in summary:
        return tuple(float(value) for value in summary["theta_grid_deg"])
    return DEFAULT_THETA_GRID_DEG


def row_slice(num_rows: int, start: int, stop: int) -> np.ndarray:
    start = int(start)
    stop = int(stop) if int(stop) else int(num_rows)
    if start >= num_rows:
        raise ValueError(f"--row-start={start} is outside dataset length {num_rows}.")
    if stop <= start or stop > num_rows:
        raise ValueError(f"Invalid row range [{start}, {stop}) for dataset length {num_rows}.")
    return np.arange(start, stop, dtype=np.int64)


def create_or_open_output(
    h5: h5py.File,
    dataset_path: str,
    shape: tuple[int, ...],
    dtype: str,
    *,
    overwrite: bool,
    compression: str,
) -> h5py.Dataset:
    if dataset_path in h5 and overwrite:
        del h5[dataset_path]
    if dataset_path in h5:
        out = h5[dataset_path]
        if out.shape != shape:
            raise RuntimeError(f"Existing dataset {dataset_path} has shape {out.shape}; expected {shape}.")
        return out
    ensure_parent_group(h5, dataset_path)
    return h5.create_dataset(
        dataset_path,
        shape=shape,
        dtype=np.dtype(dtype),
        fillvalue=np.nan,
        chunks=(1, shape[1], shape[2]),
        **compression_kwargs(compression),
    )


def reconstruct_response_patch(
    *,
    row: int,
    glon_deg: float,
    glat_deg: float,
    cmb_realization_idx: int,
    has_signal: bool,
    z0: float,
    zcrit: float,
    theta_crit_deg: float,
    edge_sigma_deg: float,
    center_x_pix: float,
    center_y_pix: float,
    injection_convention: str,
    cache: CmbMapCache,
    nside: int,
    lmax: int,
    beam_fwhm_arcmin: float,
    pixel_window_policy: str,
    noise_sigma_uk_arcmin: float,
    include_surrogate_noise: bool,
    weights_bank: dict[str, np.ndarray],
    bank_meta: dict[str, dict],
) -> np.ndarray:
    raw_map = cache.get(int(cmb_realization_idx)).copy()
    if bool(has_signal):
        raw_map = inject_signal_on_sphere(
            raw_map,
            glon_deg=float(glon_deg),
            glat_deg=float(glat_deg),
            z0=float(z0),
            zcrit=float(zcrit),
            theta_crit_deg=float(theta_crit_deg),
            edge_sigma_deg=float(edge_sigma_deg),
            center_x_pix=float((PATCH_PIX - 1) - float(center_x_pix)),
            center_y_pix=float(center_y_pix),
            injection_convention=str(injection_convention),
        ).astype(np.float64, copy=False)
    observed_map = apply_observing_transfer(
        raw_map,
        nside=int(nside),
        lmax=int(lmax),
        beam_fwhm_arcmin=float(beam_fwhm_arcmin),
        pixel_window_policy=str(pixel_window_policy),
    )
    if include_surrogate_noise and float(noise_sigma_uk_arcmin) > 0.0:
        sigma_k = fullsky_noise_sigma_k_per_pixel(float(noise_sigma_uk_arcmin), int(nside))
        rng = row_noise_rng(20260421, int(row))
        observed_map = observed_map + rng.normal(0.0, sigma_k, size=observed_map.shape)

    data_alm = hp.map2alm(validate_cmb_map(observed_map), lmax=int(lmax), iter=3)
    max_response = np.full(observed_map.shape, -np.inf, dtype=np.float32)
    for key, weights in weights_bank.items():
        norm = float(bank_meta[key]["normalization"])
        if not np.isfinite(norm) or norm <= 0.0:
            raise ValueError(f"Bank entry {key!r} has non-physical normalization {norm}.")
        response = hp.alm2map(hp.almxfl(data_alm, weights), int(nside), lmax=int(lmax)) / np.sqrt(norm)
        if bool(bank_meta[key].get("absolute_response", False)):
            response = np.abs(response)
        np.maximum(max_response, np.asarray(response, dtype=np.float32), out=max_response)
    patch = project_patch(
        max_response,
        float(glon_deg),
        float(glat_deg),
        validate_temperature_scale=False,
    )
    patch = np.asarray(patch, dtype=np.float32)
    if not np.all(np.isfinite(patch)):
        raise ValueError(f"Projected Wiener response patch for row {row} contains non-finite values.")
    return patch


def init_worker(payload: dict[str, Any]) -> None:
    """Initialize process-local cache state for spherical Wiener response rows."""

    global WORKER_STATE
    WORKER_STATE = dict(payload)
    WORKER_STATE["cache"] = CmbMapCache(
        WORKER_STATE["seeds"],
        nside=int(WORKER_STATE["nside"]),
        lmax=int(WORKER_STATE["lmax"]),
        cls_tt=np.asarray(WORKER_STATE["cls_tt"], dtype=np.float64),
        max_items=int(WORKER_STATE["cmb_realization_cache"]),
    )


def cache_row_worker(row: int) -> tuple[int, np.ndarray]:
    """Worker entry point for one HDF5 row."""

    state = WORKER_STATE
    row = int(row)
    patch = reconstruct_response_patch(
        row=row,
        glon_deg=float(state["glon_deg"][row]),
        glat_deg=float(state["glat_deg"][row]),
        cmb_realization_idx=int(state["cmb_realization_idx"][row]),
        has_signal=bool(state["has_signal"][row]),
        z0=float(state["z0"][row]),
        zcrit=float(state["zcrit"][row]),
        theta_crit_deg=float(state["theta_crit_deg"][row]),
        edge_sigma_deg=float(state["edge_sigma_deg"][row]),
        center_x_pix=float(state["signal_center_x_pix"][row]),
        center_y_pix=float(state["signal_center_y_pix"][row]),
        injection_convention=str(state["injection_convention"]),
        cache=state["cache"],
        nside=int(state["nside"]),
        lmax=int(state["lmax"]),
        beam_fwhm_arcmin=float(state["beam_fwhm_arcmin"]),
        pixel_window_policy=str(state["pixel_window_policy"]),
        noise_sigma_uk_arcmin=float(state["noise_sigma_uk_arcmin"]),
        include_surrogate_noise=bool(state["include_surrogate_noise"]),
        weights_bank=state["weights_bank"],
        bank_meta=state["bank_meta"],
    )
    return row, patch


def cache_one(path: Path, args: argparse.Namespace) -> dict[str, Any]:
    summary = load_summary(path)
    camb_params = resolve_camb_params(path, summary)
    seeds = list(camb_params.get("seeds", []))
    camb_meta = dict(camb_params.get("camb", {}))
    if not seeds:
        raise ValueError(f"{path} summary camb_params does not contain seeds.")

    nside = int(summary.get("nside", 256))
    lmax = int(args.lmax) if int(args.lmax) else 3 * nside - 1
    theta_grid_deg = resolve_theta_grid(summary, args.theta_grid_values)
    beam_fwhm_arcmin = float(summary.get("beam_fwhm_arcmin", 5.0))
    noise_sigma_uk_arcmin = float(summary.get("noise_sigma_uk_arcmin", 0.0))
    pixel_window_policy = str(summary.get("pixel_window_policy", "synfast_pixwin_true"))
    injection_convention = str(summary.get("injection_convention", "feeney2011_full_temperature_modulation"))

    cls_tt, camb_provenance = camb_tt_cls(
        lmax=int(lmax),
        params=camb_meta.get("params"),
        lens_potential_accuracy=int(camb_meta.get("lens_potential_accuracy", 1)),
    )
    weights_bank, bank_meta = precompute_wiener_feeney_filter_bank(
        nside=int(nside),
        cmb_cl=cls_tt,
        theta_grid_deg=tuple(theta_grid_deg),
        lmax=int(lmax),
        beam_fwhm_arcmin=float(beam_fwhm_arcmin),
        noise_sigma_uk_arcmin=float(noise_sigma_uk_arcmin),
        pixel_window_policy=str(pixel_window_policy),
        quadrature_order=int(args.quadrature_order),
        collapse_sign_pairs=True,
    )
    cache = CmbMapCache(
        seeds,
        nside=int(nside),
        lmax=int(lmax),
        cls_tt=cls_tt,
        max_items=int(args.cmb_realization_cache),
    )

    dataset_path = args.dataset.strip("/")
    with h5py.File(path, "r+") as h5:
        patches = h5["patches"]
        num_rows, height, width = patches.shape
        selected_rows = row_slice(num_rows, int(args.row_start), int(args.row_stop))
        out = create_or_open_output(
            h5,
            dataset_path,
            patches.shape,
            args.dtype,
            overwrite=bool(args.overwrite),
            compression=str(args.compression),
        )
        if args.dry_run:
            return {
                "h5": str(path),
                "dataset": dataset_path,
                "status": "dry_run",
                "num_rows": int(num_rows),
                "selected_rows": int(selected_rows.size),
                "theta_grid_deg": [float(x) for x in theta_grid_deg],
            }

        out.attrs["created_utc"] = dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
        out.attrs["description"] = (
            "Projected per-pixel max SNR over the spherical Wiener/Feeney matched-filter bank."
        )
        out.attrs["source_method_metadata"] = json.dumps(method_metadata(WIENER_FEENEY_MATCHED_FILTER), sort_keys=True)
        out.attrs["theta_grid_deg"] = json.dumps([float(x) for x in theta_grid_deg])
        out.attrs["beam_fwhm_arcmin"] = float(beam_fwhm_arcmin)
        out.attrs["noise_sigma_uk_arcmin"] = float(noise_sigma_uk_arcmin)
        out.attrs["pixel_window_policy"] = str(pixel_window_policy)
        out.attrs["injection_convention"] = str(injection_convention)
        out.attrs["include_surrogate_noise"] = bool(args.include_surrogate_noise)
        out.attrs["projection_caveat"] = (
            "Base HDF5 patches are patch-generated. The spherical Wiener channel matches "
            "the CMB realization and signal geometry but may not exactly match the original "
            "patch-space signal/noise realization."
        )
        out.attrs["camb_provenance"] = json.dumps(camb_provenance, sort_keys=True)

        metadata = h5["metadata"]
        truth = h5["truth"]
        pending_rows = []
        for row in selected_rows:
            row = int(row)
            existing = np.asarray(out[row], dtype=np.float32)
            if not args.overwrite and np.all(np.isfinite(existing)):
                continue
            pending_rows.append(row)

        if not pending_rows:
            return {
                "h5": str(path),
                "dataset": dataset_path,
                "status": "reused",
                "num_rows": int(num_rows),
                "selected_rows": int(selected_rows.size),
                "theta_grid_deg": [float(x) for x in theta_grid_deg],
                "include_surrogate_noise": bool(args.include_surrogate_noise),
                "row_start": int(args.row_start),
                "row_stop": int(args.row_stop) if int(args.row_stop) else int(num_rows),
            }

        # Group work by CMB realization so the small per-process synfast cache
        # can actually reuse raw skies instead of missing on near-random row
        # order from the training and sensitivity files.
        pending_rows = sorted(pending_rows, key=lambda row: int(metadata["cmb_realization_idx"][int(row)]))
        print(
            f"  {path.name}: caching {len(pending_rows)} selected rows "
            f"into {dataset_path} with workers={int(args.workers)}",
            flush=True,
        )

        if int(args.workers) == 1:
            rows_done = 0
            for row in pending_rows:
                response_patch = reconstruct_response_patch(
                    row=row,
                    glon_deg=float(metadata["glon_deg"][row]),
                    glat_deg=float(metadata["glat_deg"][row]),
                    cmb_realization_idx=int(metadata["cmb_realization_idx"][row]),
                    has_signal=bool(truth["has_signal"][row]),
                    z0=float(truth["z0"][row]),
                    zcrit=float(truth["zcrit"][row]),
                    theta_crit_deg=float(truth["theta_crit_deg"][row]),
                    edge_sigma_deg=float(truth["edge_sigma_deg"][row]) if "edge_sigma_deg" in truth else 0.0,
                    center_x_pix=float(truth["signal_center_x_pix"][row]),
                    center_y_pix=float(truth["signal_center_y_pix"][row]),
                    injection_convention=str(injection_convention),
                    cache=cache,
                    nside=int(nside),
                    lmax=int(lmax),
                    beam_fwhm_arcmin=float(beam_fwhm_arcmin),
                    pixel_window_policy=str(pixel_window_policy),
                    noise_sigma_uk_arcmin=float(noise_sigma_uk_arcmin),
                    include_surrogate_noise=bool(args.include_surrogate_noise),
                    weights_bank=weights_bank,
                    bank_meta=bank_meta,
                )
                out[row] = response_patch.astype(np.dtype(args.dtype), copy=False)
                rows_done += 1
                if rows_done % 25 == 0 or rows_done == len(pending_rows):
                    h5.flush()
                    print(f"  {path.name}: cached {rows_done} / {len(pending_rows)} selected rows", flush=True)
        else:
            worker_payload = {
                "glon_deg": np.asarray(metadata["glon_deg"][:], dtype=np.float64),
                "glat_deg": np.asarray(metadata["glat_deg"][:], dtype=np.float64),
                "cmb_realization_idx": np.asarray(metadata["cmb_realization_idx"][:], dtype=np.int64),
                "has_signal": np.asarray(truth["has_signal"][:], dtype=np.uint8),
                "z0": np.asarray(truth["z0"][:], dtype=np.float64),
                "zcrit": np.asarray(truth["zcrit"][:], dtype=np.float64),
                "theta_crit_deg": np.asarray(truth["theta_crit_deg"][:], dtype=np.float64),
                "edge_sigma_deg": (
                    np.asarray(truth["edge_sigma_deg"][:], dtype=np.float64)
                    if "edge_sigma_deg" in truth
                    else np.zeros(num_rows, dtype=np.float64)
                ),
                "signal_center_x_pix": np.asarray(truth["signal_center_x_pix"][:], dtype=np.float64),
                "signal_center_y_pix": np.asarray(truth["signal_center_y_pix"][:], dtype=np.float64),
                "injection_convention": str(injection_convention),
                "nside": int(nside),
                "lmax": int(lmax),
                "beam_fwhm_arcmin": float(beam_fwhm_arcmin),
                "pixel_window_policy": str(pixel_window_policy),
                "noise_sigma_uk_arcmin": float(noise_sigma_uk_arcmin),
                "include_surrogate_noise": bool(args.include_surrogate_noise),
                "weights_bank": weights_bank,
                "bank_meta": bank_meta,
                "seeds": seeds,
                "cls_tt": cls_tt,
                "cmb_realization_cache": int(args.cmb_realization_cache),
            }
            rows_done = 0
            with ProcessPoolExecutor(
                max_workers=int(args.workers),
                initializer=init_worker,
                initargs=(worker_payload,),
            ) as executor:
                futures = [executor.submit(cache_row_worker, int(row)) for row in pending_rows]
                for future in as_completed(futures):
                    row, response_patch = future.result()
                    out[int(row)] = np.asarray(response_patch, dtype=np.dtype(args.dtype), copy=False)
                    rows_done += 1
                    if rows_done % 25 == 0 or rows_done == len(pending_rows):
                        h5.flush()
                        print(f"  {path.name}: cached {rows_done} / {len(pending_rows)} selected rows", flush=True)
        h5.flush()

    return {
        "h5": str(path),
        "dataset": dataset_path,
        "status": "created_or_updated",
        "num_rows": int(num_rows),
        "selected_rows": int(selected_rows.size),
        "computed_rows": int(len(pending_rows)),
        "theta_grid_deg": [float(x) for x in theta_grid_deg],
        "include_surrogate_noise": bool(args.include_surrogate_noise),
        "row_start": int(args.row_start),
        "row_stop": int(args.row_stop) if int(args.row_stop) else int(num_rows),
    }


def main() -> None:
    args = parse_args()
    validate_args(args)
    outputs = [cache_one(path, args) for path in args.h5_paths]
    print(
        json.dumps(
            {
                "dataset": args.dataset,
                "outputs": outputs,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
